In [1]:
# Import Required Libraries

import pandas as pd
import numpy as np

In [2]:
# Load Dataset Using Pandas

df = pd.read_csv("/content/Retail_Dataset_Cleaned 10.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [ ]:
# Display First Five Records

df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6,57,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4,99,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4,101,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5,79,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2,110,1,2022,Q1,Spring

In [ ]:
# Check Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   int64
 11  Units_Sold             5146 non-null   int64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   int64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   int64
 42  Shipping_Cost          5146 non-null   int64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(10), int64(15), object(22)
memory usage: 1.8+ MB

In [ ]:
# Display Column Names

df.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [ ]:
# Create Category-wise Revenue Pivot Table

category_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc="sum"
)

category_revenue

                    Revenue
Category
Clothes           222062999
Electronics      3623062916
Gadgets          2654378776
Groceries          23940283
Home Appliances   558411929

In [ ]:
# Create City-wise Units Sold Pivot Table

city_sales = pd.pivot_table(
    df,
    values="Units_Sold",
    index="City",
    aggfunc="sum"
)
city_sales

               Units_Sold
City
Ahmedabad            9784
Bangalore           24384
Bhopal               4216
Chennai             23674
Delhi               52516
Hyderabad           22449
Jaipur               9909
Kanpur               3419
Lucknow              3530
Mumbai              46679
Nagpur               4182
Pune                11115
Surat                8859
Visakhapatnam        3767

In [ ]:
# Create Customer Segment-wise Revenue Report

segment_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Customer_Segment",
    aggfunc="sum"
)

segment_revenue

                     Revenue
Customer_Segment
Budget            1712614869
Luxury            1863606121
Mid-Range         1822547871
Premium           1683088042

In [ ]:
# Task 2: Aggregating Retail Data for Business Decision-Making
# Calculate Multiple Revenue Statistics Category-wise

category_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc=["sum", "mean", "max", "min"]
)

category_summary

                        sum          mean       max     min
                    Revenue       Revenue   Revenue Revenue
Category
Clothes           222062999  1.717425e+05   1245972    4985
Electronics      3623062916  2.769926e+06  11182353  120655
Gadgets          2654378776  2.594701e+06  23343582    9295
Groceries          23940283  2.365641e+04    350176     840
Home Appliances   558411929  1.094925e+06   6588592   81333

In [8]:
# Aggregate Units Sold by Sales Channel

channel_summary = pd.pivot_table(
    df,
    values="Units_Sold",
    index="Sales_Channel",
    aggfunc=["sum", "mean"]
)

channel_summary

                                    sum       mean
                             Units_Sold Units_Sold
Sales_Channel
Brandx_India App                  45472  44.190476
Brandx_India Online               44598  43.982249
Brandx_India Phone Order          44919  44.342547
Brandx_India Social Commerce      44695  45.329615
Brandx_India Store                48799  44.201993

In [9]:
# Aggregate Revenue and Profit Margin by City

city_performance = pd.pivot_table(
    df,
    values=["Revenue", "Profit_Margin"],
    index="City",
    aggfunc={
        "Revenue": "sum",
        "Profit_Margin": "mean"
    }
)
city_performance

               Profit_Margin     Revenue
City
Ahmedabad          22.624845   265527609
Bangalore          22.830374   840799728
Bhopal             22.620614   107989533
Chennai            22.259758   741911598
Delhi              22.282928  1661121901
Hyderabad          22.239853   659795773
Jaipur             22.326377   267094484
Kanpur             22.539515    84302178
Lucknow            22.070538    94862211
Mumbai             22.435763  1674840467
Nagpur             22.342162    74798793
Pune               22.756934   293682915
Surat              22.883691   234063358
Visakhapatnam      22.574245    81066355

In [10]:
# Create Store Type Performance Report

store_summary = pd.pivot_table(
    df,
    values=["Revenue", "Units_Sold"],
    index="Store_Type",
    aggfunc="sum"
)

store_summary

                 Revenue  Units_Sold
Store_Type
Express       1438935543       45493
Flagship      1413565579       46443
Mall Store    1492527140       47919
Online Hub    1442169726       44442
Street Store  1294658915       44186

In [14]:
# Category wise minimum unit sold,maximum revenue and total profit margin
category_revenue = pd.pivot_table(
    df,
    values=["Revenue", "Units_Sold" , "Profit_Margin"],
    index="Category",
    aggfunc={
        "Revenue": "max",
        "Units_Sold": "min",
        "Profit_Margin": "sum"
    }
)
category_revenue

                 Profit_Margin   Revenue  Units_Sold
Category
Clothes               28807.73   1245972           4
Electronics           29587.41  11182353           5
Gadgets               22967.11  23343582           5
Groceries             22719.09    350176          20
Home Appliances       11437.67   6588592           5